# pyproject.toml
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "funcbuilder"
version = "2.1.0"

[tool.setuptools.packages]
# Pure Python packages/modules
find = { where = ["python"] }


